version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: prova
      MYSQL_USER: provauser
      MYSQL_PASSWORD: contra
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data:


