version: '3.9'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php-server
    tty: true
    stdin_open: true
    depends_on:
      - mysql
    ports:
      - 80:80
    volumes:
      - ./website:/var/www/html  

  db:
    container_name: conetendor_mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    tty: true
    stdin_open: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "test_db"
      MYSQL_USER: "devuser"
      MYSQL_PASSWORD: ""